language: rust

cache:
  directories:
  - "$HOME/.cargo"
  - "$HOME/.cache"

services:
- docker

jobs:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu OUTPUT=dsfd CARGO=cross
    os: linux
  - env: TARGET=armv7-unknown-linux-gnueabihf OUTPUT=dsfd CARGO=cross
    os: linux
  - env: TARGET=x86_64-apple-darwin OUTPUT=dsfd CARGO=cargo
    os: osx
  - env: TARGET=i686-pc-windows-msvc OUTPUT=dsfd.exe CARGO=cargo
    os: windows

  allow_failures:
  - os: windows

install:
- cargo fetch
- rustup target add $TARGET
- rustup component add rustfmt
- cargo install cross || true

script:
- "$CARGO test"
- "$CARGO build --target $TARGET --release"
- if [[ $OS == 'linux' ]]; then cargo deb --no-build --target $TARGET; fi
- tar -cvf target/dsfd-$TARGET-$TRAVIS_TAG.tgz -C target/$TARGET/release/ $OUTPUT

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: releases
  api_key:
    secure: hjIVGBTRo4zbyVYGGIsq8oL6umqO8UFEubTKbGYrWoexL2dFwuzcuIU6nrS4OyAtsYrDeLPbCkzB7fXznJi9FiJNUGYhisImHr5f6Ds8k/OBk7gJimWY0dlixHjv7WnbTCopoN7DQiHIG2rKYcy7pLGmXK0Xo9Z432tBhCtE/u7Rietc4funIpojI24GA81mCcZbxLmiSJ3OC1H/2ZzQj/FzA2ZUgqA+v0KdsJfFGhxYNalFSM0He1RtzPpei9x1cPreNHwOn6Sbz3Ar3QhVugDcWPE9t9uNiTkK1UgdQCnk5u6pquqgJxcNKASeA8VI2LJ7SBuix35Ov7ZsbkOe3yBn06l1Qom5h71QwlrBD/Ls/K+0KLJ60w9snEXuMTHlxZ2SgJKqqHmVCaIvL6c54YwYoFBJCg7W6K0p7oAn498ACUZ0MRUVHiESfVjlrxeXgaPAnGNqgUlM0YEoAtThja7cvWAUEUwkEUwzH7LU8GcBIQY/yYEVfo/ZmGwEBQb0XVsKt8DtOOPuyxVad35UfGY19kcXDsM54M4kgEpPOhkD8ki5KqIEQ8Lt1/uZ+HT/LIB4EjHjz3UGH8t0wXOqu+BlUrRpiVYd8TZ9MhK3g3o7FeqaTv1wl+9AYh6mWJl3FDhK/aFhvqKJD1IkWkyeVVAYTvJmpBU++t82h5+9x4c=
  file: 
    - "target/*.tgz"
    - "target/$TARGET/debian/*.deb"
  file_glob: true
  on:
    repo: dist-svc/dsf-daemon
    tags: true
  skip_cleanup: 'true'
