[package]
name = "dsf-daemon"
repository = "https://github.com/dist-svc/dsf-daemon"
version = "0.1.0"
authors = ["ryan <ryan@kurte.nz>"]
edition = "2018"
license = "GPL-3.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cli = [ "structopt", "simplelog", "humantime" ]
default = [ "cli" ]


[dependencies]
futures = "0.3.1"
async-std = "1.3.0"
colored = "1.9.0"
tracing = "0.1.10"
tracing-futures = "0.2.0"
tracing-subscriber = "0.1.6"
futures_codec = "0.3.4"
async-trait = "0.1.21"
bytes = "0.5.3"
derive_builder = "0.9.0"
serde_json = "1.0.44"
base64 = "0.11.0"
chrono-humanize = "0.0.11"
tempdir = "0.3.7"
bitflags = "1.2.1"

[dependencies.dsf-core]
version = "0.1.0"
features = [ "serde" ]

[dependencies.dsf-rpc]
version = "*"
path = "../dsf-rpc"


[dependencies.kad]
version = "*"
path = "../rust-kad"

[dependencies.log]
features = ["max_level_trace", "release_max_level_info"]
version = "0.4.6"

[dependencies.diesel]
features = [ "sqlite" ]
version = "1.4.3"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.6"

[dependencies.structopt]
version = "0.3.5"
optional = true

[dependencies.simplelog]
version = "0.7.4"
optional = true

[dependencies.humantime]
version = "*"
optional = true

[[bin]]
name = "dsfc"
path = "src/main.rs"
required-features = [ "cli" ]

[patch.crates-io]
futures_codec = { git = "https://github.com/ryankurte/futures-codec", branch = "feature/json-cbor-codecs" }

[dev-dependencies]
tempdir = "0.3.7"
rr-mux = "0.10.1"
rand = "0.7.3"
