name: Rust CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Configure caching
        uses: actions/cache@v2
        with:
          key: check
          path: |
            ${{ env.HOME }}/.cargo
            ./target

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Configure caching
        uses: actions/cache@v2
        with:
          key: test
          path: |
            ${{ env.HOME }}/.cargo
            ./target
        
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
    
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            output: dsfd
          - target: armv7-unknown-linux-gnueabihf 
            os: ubuntu-latest
            output: dsfd
          - target: x86_64-apple-darwin
            os: macos-latest
            output: dsfd

    steps:
    - uses: actions/checkout@v2
      
    - name: Configure toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target:  ${{ matrix.target }}
        override: true
    
    - name: Configure caching
      uses: actions/cache@v2
      with:
        key: build-${{ matrix.os }}-${{ matrix.target }}
        path: |
          ${{ env.HOME }}/.cargo
          ./target
    
    - name: Install cross toolchain (armv7)
      if: ${{ matrix.target == 'armv7-unknown-linux-gnueabihf' }}
      run: sudo apt-get install gcc-arm-linux-gnueabihf

    - name: Enable cross compilation (armv7)
      if: ${{ matrix.target == 'armv7-unknown-linux-gnueabihf' }}
      run: |
        echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use_cross }}
        command: build
        args: --release --target ${{ matrix.target }}
    
    - name: Create archive
      run: tar -cvf target/dsfd-${{ matrix.target }}.tgz -C target/${{ matrix.target }}/release/ ${{ matrix.output }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dsfd-${{ matrix.target }}.tgz
        path: target/dsfd-${{ matrix.target }}.tgz
      
    - name: Upload release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/dsfd-${{ matrix.target }}.tgz
        asset_name: dsfd-${{ matrix.target }}.tgz
        tag: ${{ github.ref }}
        overwrite: true

  images:
    name: Build Images
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch environmental variables
        uses: FranzDiebold/github-env-vars-action@v2.1.0

      - uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build
        run: |
          docker buildx build --platform linux/arm/v7,linux/amd64 -t github.com/dist-svc/dsf-daemon:${{ CI_SHA_SHORT }}
