name: Rust CI test / build / deploy

on:
  push: []
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
    
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            output: dsfd
            use_cross: false
            experimental: false
          - target: armv7-unknown-linux-gnueabihf 
            os: ubuntu-latest
            output: dsfd
            use_cross: true
            experimental: false
          - target: x86_64-apple-darwin
            os: macos-latest
            output: dsfd
            use_cross: false
            experimental: true
          - target: i686-pc-windows-msvc
            os: windows-latest
            output: dsfd.exe
            use_cross: false
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target:  ${{ matrix.target }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use_cross }}
        command: build
        args: --target ${{ matrix.target }}
    outputs:
      bin: target/${{ matrix.target }}/release/${{ matrix.output }}
      
   
