name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
    
  build:
    name: Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            output: dsfd
            use_cross: false 
          - target: armv7-unknown-linux-gnueabihf 
            output: dsfd
            use_cross: true
          - target: i686-pc-windows-msvc
            output: dsfd.exe
            use_cross: false 
          - target: x86_64-apple-darwin
            output: dsfd
            use_cross: false 

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target:  ${{ matrix.target }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: ${{ matrix.use_cross }}
        command: build
        args: --target ${{ matrix.target }}

      
   
